default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: password
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: arkena_dev

test:
  <<: *default
  database: arkena_test

production:
  <<: *default
  database: arkena_prod
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
