name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: arkena_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U rails"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/arkena_test
      DEVISE_JWT_SECRET_KEY: e7df8f945dc66e1e508becf22a1b60114502710573f46570925ebb31ec32addfed4a9e915340f52107d2511230cd5e8b96bb1af887ce77e293b3367a5b9a5f57

    steps:
      - uses: actions/checkout@v5

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: RuboCop
        run: bundle exec rubocop

      - name: Brakeman
        run: bundle exec brakeman -q

      - name: RSpec
        run: bundle exec rspec --format progress
